use jsonwebtoken::{decode, DecodingKey, Validation, Algorithm};
use serde::{Deserialize, Serialize};
use std::fs;

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    pub sub: String,
    pub email: String,
    pub plan: String, 
    pub exp: usize,
    pub iat: usize,
    pub iss: String,
}

#[derive(Debug)]
pub enum AuthError {
    InvalidToken,
    Expired,
    NotPremium,
    KeyMissing,
}

pub fn verify_premium_access(jwt: &str) -> Result<Claims, AuthError> {
    // Read the Ed25519 public key generated by our Next.js web platform
    let public_key_pem = fs::read_to_string("keys/public.pem")
        .unwrap_or_else(|_| String::from("-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----"));

    let decoding_key = DecodingKey::from_ed_pem(public_key_pem.as_bytes())
        .map_err(|_| AuthError::InvalidToken)?;

    let mut validation = Validation::new(Algorithm::EdDSA);
    validation.set_issuer(&["cipher64"]);

    decode::<Claims>(jwt, &decoding_key, &validation)
        .map(|data| data.claims)
        .map_err(|err| match err.kind() {
            jsonwebtoken::errors::ErrorKind::ExpiredSignature => AuthError::Expired,
            _ => AuthError::InvalidToken,
        })
        .and_then(|claims| {
            if claims.plan == "premium" {
                Ok(claims)
            } else {
                Err(AuthError::NotPremium)
            }
        })
}