/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/databases': typeof DatabasesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/databases': typeof DatabasesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/databases': typeof DatabasesRoute
  '/learn': typeof LearnRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boards' | '/databases' | '/learn' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boards' | '/databases' | '/learn' | '/settings'
  id: '__root__' | '/' | '/boards' | '/databases' | '/learn' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  DatabasesRoute: typeof DatabasesRoute
  LearnRoute: typeof LearnRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  DatabasesRoute: DatabasesRoute,
  LearnRoute: LearnRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
